"""create all tables

Revision ID: 7a08a0ba99e2
Revises: 3d4054736ef0
Create Date: 2026-06-28 13:12:49.892912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a08a0ba99e2'
down_revision: Union[str, Sequence[str], None] = '3d4054736ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('feature', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('raw_prompt', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('ai_output', sa.Text(), nullable=True),
    sa.Column('structured_output', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('file_bucket', sa.String(), nullable=True),
    sa.Column('file_key', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('ocr_status', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.Column('encryption_key_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('input_type', sa.String(), nullable=True),
    sa.Column('symptom_tags', sa.Text(), nullable=True),
    sa.Column('body_parts_affected', sa.Text(), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('triggers', sa.Text(), nullable=True),
    sa.Column('relieving_factors', sa.Text(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('affects_work', sa.Boolean(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('medications_taken', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('pattern_type', sa.String(), nullable=True),
    sa.Column('related_symptom_ids', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('suggested_action', sa.String(), nullable=True),
    sa.Column('user_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_health_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('biological_sex', sa.String(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('past_surgeries', sa.Text(), nullable=True),
    sa.Column('primary_physician', sa.String(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_insurance_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('insurer_name', sa.String(), nullable=True),
    sa.Column('member_id', sa.String(), nullable=True),
    sa.Column('group_number', sa.String(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.Column('deductible_total', sa.Float(), nullable=True),
    sa.Column('deductible_met', sa.Float(), nullable=True),
    sa.Column('out_of_pocket_max', sa.Float(), nullable=True),
    sa.Column('out_of_pocket_met', sa.Float(), nullable=True),
    sa.Column('coverage_start', sa.Date(), nullable=True),
    sa.Column('coverage_end', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('front_card_key', sa.String(), nullable=True),
    sa.Column('back_card_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('insurance_plan_id', sa.UUID(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('provider_npi', sa.String(), nullable=True),
    sa.Column('provider_address', sa.String(), nullable=True),
    sa.Column('facility_type', sa.String(), nullable=True),
    sa.Column('total_billed', sa.Float(), nullable=True),
    sa.Column('total_allowed', sa.Float(), nullable=True),
    sa.Column('total_paid_by_insurance', sa.Float(), nullable=True),
    sa.Column('patient_responsibility', sa.Float(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('amount_disputed', sa.Float(), nullable=True),
    sa.Column('bill_status', sa.String(), nullable=True),
    sa.Column('dispute_status', sa.String(), nullable=True),
    sa.Column('claim_number', sa.String(), nullable=True),
    sa.Column('service_date_start', sa.Date(), nullable=True),
    sa.Column('service_date_end', sa.Date(), nullable=True),
    sa.Column('bill_received_date', sa.Date(), nullable=True),
    sa.Column('diagnosis_codes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['user_insurance_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('procedure_name', sa.String(), nullable=True),
    sa.Column('procedure_code', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('facility_name', sa.String(), nullable=True),
    sa.Column('procedure_date', sa.Date(), nullable=True),
    sa.Column('anesthesia_type', sa.String(), nullable=True),
    sa.Column('risks_identified', sa.Text(), nullable=True),
    sa.Column('alternatives_listed', sa.Text(), nullable=True),
    sa.Column('patient_signed', sa.Boolean(), nullable=True),
    sa.Column('decode_status', sa.String(), nullable=True),
    sa.Column('plain_language_summary', sa.Text(), nullable=True),
    sa.Column('questions_to_ask', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appeal_letters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('appeal_type', sa.String(), nullable=True),
    sa.Column('letter_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sent_via', sa.String(), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('sent_date', sa.Date(), nullable=True),
    sa.Column('response_id', sa.String(), nullable=True),
    sa.Column('response_outcome', sa.String(), nullable=True),
    sa.Column('amount_recovered', sa.Float(), nullable=True),
    sa.Column('insurer_response_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=True),
    sa.Column('cpt_code', sa.String(), nullable=True),
    sa.Column('cpt_description', sa.String(), nullable=True),
    sa.Column('revenue_code', sa.String(), nullable=True),
    sa.Column('modifier_codes', sa.String(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('billed_amount', sa.Float(), nullable=True),
    sa.Column('allowed_amount', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('patient_portion', sa.Float(), nullable=True),
    sa.Column('flag_type', sa.String(), nullable=True),
    sa.Column('flag_reason', sa.String(), nullable=True),
    sa.Column('potential_savings', sa.Float(), nullable=True),
    sa.Column('is_disputed', sa.Boolean(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_line_items')
    op.drop_table('appeal_letters')
    op.drop_table('consent_forms')
    op.drop_table('bills')
    op.drop_table('user_insurance_plans')
    op.drop_table('user_health_profiles')
    op.drop_table('symptom_patterns')
    op.drop_table('symptom_entries')
    op.drop_table('notifications')
    op.drop_table('documents')
    op.drop_table('audit_logs')
    op.drop_table('ai_results')
    # ### end Alembic commands ###
